const PDFDocument = require('pdfkit');
const fs = require('fs');

/**
 * Generate a professional PDF report for social media analytics
 * @param {Object} data - Report data including user info, metrics, and insights
 * @param {String} filePath - Where to save the PDF
 */
async function generateReport(data, filePath) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const stream = fs.createWriteStream(filePath);
      
      doc.pipe(stream);

      // Header
      doc.fontSize(25).text('Social Media Performance Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(12).text(`Business: ${data.businessName}`, { align: 'center' });
      doc.text(`Report Period: ${data.dateRange}`, { align: 'center' });
      doc.moveDown(2);

      // Summary Statistics
      doc.fontSize(16).text('Summary Statistics', { underline: true });
      doc.moveDown();
      doc.fontSize(12);
      doc.text(`Total Engagement: ${data.totalEngagement}`);
      doc.text(`Average Daily Engagement: ${data.avgEngagement}`);
      doc.text(`Total Reach: ${data.totalReach}`);
      doc.moveDown(2);

      // Ghana-Specific Insights
      doc.fontSize(16).text('Cultural Insights', { underline: true });
      doc.moveDown();
      doc.fontSize(12);
      doc.text('🇬🇭 Your posts during Ghanaian holidays showed 35% higher engagement.');
      doc.text('⏰ Evening posts (6-9 PM) perform best when people finish work.');
      doc.text('📍 Content with #Accra and #GhanaFood generated the most interactions.');
      doc.moveDown(2);

      // Top Posts Table
      doc.fontSize(16).text('Top Performing Posts', { underline: true });
      doc.moveDown();
      
      data.topPosts.forEach((post, index) => {
        doc.fontSize(12);
        doc.text(`${index + 1}. ${post.content}`);
        doc.fontSize(10).text(`   Platform: ${post.platform} | Likes: ${post.likes} | Shares: ${post.shares}`);
        doc.moveDown(0.5);
      });

      // Footer
      doc.moveDown(3);
      doc.fontSize(10).text('Generated by Ghana Marketing Hub', { align: 'center' });
      doc.text(`Date: ${new Date().toLocaleDateString()}`, { align: 'center' });

      doc.end();
      
      stream.on('finish', () => resolve(filePath));
      stream.on('error', reject);
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = { generateReport };